# Generated by Django 3.0.5 on 2020-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='books',
            name='published_at',
            field=models.TextField(),
        ),
    ]
