# Generated by Django 3.0.5 on 2020-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(blank=True, to='Books.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
