# Generated by Django 3.0.5 on 2020-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20200412_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True),
        ),
    ]
