# Generated by Django 3.0.5 on 2020-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20200412_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_num_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
