# Generated by Django 3.0.5 on 2020-04-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserGroups', '0002_auto_20200414_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='my_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
