# Generated by Django 3.0.5 on 2020-04-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20200412_2021'),
        ('UserGroups', '0003_auto_20200415_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('book', models.ManyToManyField(blank=True, to='Books.Book')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserGroups.UserGroup')),
            ],
        ),
    ]
