# Generated by Django 2.2.3 on 2020-04-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserGroups', '0006_auto_20200417_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
